### ISSUE TITLE
Docker container labels - Issues with the Scopes argument

### ISSUE THREAD

**Issue by edrf12** [sevensolutions/traefik-oidc-auth#14]
Hi, this plugin is amazing, but I ran into an issue when trying to use docker labels to create a middleware.

My labels look like this

```yaml
- traefik.enable=true
- traefik.http.routers.<router>.rule=Host(`something.example.com`)
- traefik.http.routers.<router>.middlewares=auth
- traefik.http.routers.<router>.priority=40
- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.provider.url=https://idm.example.com/oauth2/openid/<clientid>
- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.provider.usepkce=true
- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.provider.clientid=<clientid>
- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.provider.clientsecret=<clientsecret>
```

All of those work fine, but I couldn't manage to set the scopes, I've tried the following labels
```
- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.scopes=<scope>
- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.scopes[0]=<scope>
```

**Comment by edrf12** [comment]
I just tried creating a service with the label

`- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.scopes=openid`

And when I tried to login I see that it requested to my service the default scopes (openid, email and profile)

I also tried

`- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.scopes=openid,profile`

And I got the same result

**Comment by sevensolutions** [comment]
Ok so after a few more tests: You can supply default values in `func CreateConfig() *Config`, but not for arrays.
Seems like a traefik bug to me.

**Comment by sevensolutions** [comment]
Release is out 🎉

**Comment by edrf12** [comment]
@sevensolutions It seems that this also affects MapClaims and AssertClaims as the following labels do not set MapClaims successfully

```yaml
- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.headers.mapclaims[0].claim=preferred_username
- traefik.http.middlewares.auth.plugin.traefik-oidc-auth.headers.mapclaims[0].header=X-Auth-Sub
```

I haven't tested AssertClaims but I assume it will have the same issue.

**Comment by sevensolutions** [comment]
@edrf12 hmm, i cannot reproduce this.
I've temporarily added this debug output at the end of the `New()` method to see the configuration.

```go
for _, val := range config.Headers.MapClaims {
	log(config.LogLevel, LogLevelDebug, "MapClaim: %s -> %s", val.Claim, val.Header)
}
```

Using your labels i get:

```
2024-10-26 07:23:51 [DEBUG] [traefik-oidc-auth] MapClaim: preferred_username -> X-Auth-Sub
```

**Comment by sevensolutions** [comment]
@edrf12 what happens, if you also request the "email" scope?
Because i had a similar issue with EntraID where i didn't get the preferred_username because of this missing scope.

**Comment by edrf12** [comment]
@sevensolutions I tried requesting openid,email,profile and have the same issue.

**Comment by edrf12** [comment]
To complement my response here is a request to the idm (Kanidm) with oauth2c (OAuth2 CLI)

Command:
```shell
oauth2c https://idm.example.com/oauth2/openid/{client_id} --client-id {client_id} --client-secret {client_secret} --scopes openid,profile --pkce --grant-type authorization_code
```

Token Response:
```shell
POST https://idm.example.com/oauth2/token
Headers:
  Content-Type: application/x-www-form-urlencoded
  Authorization: Basic {BASE64-ENCODE(ClientID:ClientSecret)}
Form post:
  grant_type: authorization_code
  redirect_uri: http://localhost:9876/callback
  code: {code}
  code_verifier: {code_verifier}
Response:
{
  "access_token": "{access_token (Relevant information below)}",
  "expires_in": 900,
  "id_token": "{id_token (Relevant information below)}",
  "refresh_token": "{refresh_token}",
  "scope": "openid profile",
  "token_type": "Bearer"
}
Access token:
{
  "aud": "{client_id}",
  "client_id": "{client_id}",
  "exp": 1730342019,
  "iat": 1730341119,
  "iss": "https://idm.example.com/oauth2/openid/{client_id}",
  "jti": null,
  "nbf": 1730341119,
  "nonce": "{nonce}",
  "parent_session_id": "{parent_session_id}",
  "scope": "openid profile",
  "session_id": "{session_id}",
  "sub": "{sub}"
}
ID token:
{
  "aud": "{client_id}",
  "azp": "{client_id}",
  "exp": 1730342019,
  "iat": 1730341119,
  "iss": "https://idm.example.com/oauth2/openid/{client_id}",
  "name": "Eduardo",
  "nbf": 1730341119,
  "nonce": "{nonce}",
  "preferred_username": "edrf@idm.example.com",
  "scopes": ["openid", "profile"],
  "sub": "{sub}"
}
```

And we can see that the idm does supply us the preferred_username.

**Comment by edrf12** [comment]
For what I could gather from my tests the plugin only grabs values present in the access token but not from the ID token.

Is this intended? From what I could understand using values from the id token is not recommended because those can change?

**Comment by sevensolutions** [comment]
@edrf12 Yes exactly. Right now i'am only inspecting the access token, not the id token.
I need to do a bit of research to check whats the "correct" way of doing that but i also have another problem with EntraID because of using the access token.
I have some ideas of how to rework this logic but this will take some time.

**Comment by sevensolutions** [comment]
With version 0.4.1 you can choose whether you want to use the `access_token` or `id_token` by using the `TokenValidation` configuration option. See `https://traefik-oidc-auth.sevensolutions.cc/docs/getting-started/middleware-configuration`.

**Comment by sevensolutions** [comment]
@droplet-js 
1. Are you using version 0.4.1?
2. What do you want to set mapclaims or assertClaims or both?
3. Do you get an error or what exactly is the problem you're facing?

**Comment by sevensolutions** [comment]
@droplet-js 
Ok thx, can you somehow inspect the token you're receiving in [jwt.io](https://jwt.io)?
Does it really contain the "email" claim?
The plugin by default uses the accessToken but you can try to switch this to use the Id token like so:
```
- "traefik.http.middlewares.traefikauth.plugin.traefikoidc.provider.tokenValidation=IdToken
```

Maybe this helps...

You can also try to write `authorization.assertClaims[0].name=email"` instead of `authorization.assert_claims[0].name=email"`.
Unfortunately I don't really know what the exact notation for tags is, because i don't really use them.
