### ISSUE TITLE
Claims with `:` are reported as not found

### ISSUE THREAD

**Issue by KundaPanda** [sevensolutions/traefik-oidc-auth#26]
I am using claims that have `:` in their name, but this plugin doesn't seem to handle them correctly.

With debug logging, I get the `Unauthorized. Unable to find claim my:zitadel:grants in token claims.` error, but the `my:zitadel:grants` claim is then listed as an available claim with the correct value.

I have worked around this by adding another claim without colons, but I would prefer to only keep the `my:zitadel:grants` one.

**Comment by sevensolutions** [comment]
@KundaPanda sorry for the issue you're facing.
Can you please show me your `AssertClaims`-configuration?

**Comment by KundaPanda** [comment]
> @KundaPanda sorry for the issue you're facing. Can you please show me your `AssertClaims`-configuration?

Absolutely, here is the full configuration.

By the way, thank you very much for your work. I really appreciate it.

```
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc
  namespace: kube-system

spec:
  plugin:
    traefik-oidc-auth:
      Provider:
        Url: "..."
        ClientId: "..."
        UsePkce: true
      Scopes: ["openid", "profile", "email", "my:zitadel:grants", "grants"]
      Authorization:
        AssertClaims:
          - Name: "my:zitadel:grants"
            AnyOf: ["123:apps:member", "123:apps:admin"]
      Headers:
        MapClaims:
          - Claim: "preferred_username"
            Name: "X-Oidc-User"
          - Claim: "sub"
            Name: "X-Oidc-User"
          - Claim: "my:zitadel:grants"
            Name: "X-Oidc-Groups"
```

**Comment by sevensolutions** [comment]
@KundaPanda I was able to reproduce this and it looks like this is an issue because I'am accessing the field using jsonpath.
Putting the name in square brackets should do the trick:

```yml
Authorization:
  AssertClaims:
    - Name: "['my:zitadel:grants']"
      AnyOf: ["123:apps:member", "123:apps:admin"]
```

I will put this into the documentation.
