### ISSUE TITLE
token is malformed error when using zitadel

### ISSUE THREAD

**Issue by vanlueckn** [sevensolutions/traefik-oidc-auth#8]
I tried this package with ZITADEL. How did you configure the zitadel project and app?

With my config i get this error after login:

`token is malformed: token contains an invalid number of segments`

**Comment by sevensolutions** [comment]
Hi @vanlueckn 
this is my ZITADEL config:

Application Type: Web
Response Types: Code
Authentication Method: Basic
Grant Types: Authorization Code

Under "Token Settings" make sure you set Auth Token Type to JWT.
I think this is the cause for this error.

**Comment by vanlueckn** [comment]
Thank you, it does work now
